<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\eventstore\\abstracteventstream' => '/../vendor/spriebsch/eventstore/src/stream/AbstractEventStream.php',
                'spriebsch\\eventstore\\classdoesnotimplementeventinterfaceexception' => '/../vendor/spriebsch/eventstore/src/event/ClassDoesNotImplementEventInterfaceException.php',
                'spriebsch\\eventstore\\correlationid' => '/../vendor/spriebsch/eventstore/src/event/CorrelationId.php',
                'spriebsch\\eventstore\\correlationidhaschangedexception' => '/../vendor/spriebsch/eventstore/src/sourcing/CorrelationIdHasChangedException.php',
                'spriebsch\\eventstore\\emitseventstrait' => '/../vendor/spriebsch/eventstore/src/events/EmitsEventsTrait.php',
                'spriebsch\\eventstore\\emptyeventscollectionexception' => '/../vendor/spriebsch/eventstore/src/events/EmptyEventsCollectionException.php',
                'spriebsch\\eventstore\\event' => '/../vendor/spriebsch/eventstore/src/event/Event.php',
                'spriebsch\\eventstore\\eventfactory' => '/../vendor/spriebsch/eventstore/src/event/EventFactory.php',
                'spriebsch\\eventstore\\eventfactorynotconfiguredexception' => '/../vendor/spriebsch/eventstore/src/event/EventFactoryNotConfiguredException.php',
                'spriebsch\\eventstore\\eventid' => '/../vendor/spriebsch/eventstore/src/event/EventId.php',
                'spriebsch\\eventstore\\eventreader' => '/../vendor/spriebsch/eventstore/src/eventstore/EventReader.php',
                'spriebsch\\eventstore\\events' => '/../vendor/spriebsch/eventstore/src/events/Events.php',
                'spriebsch\\eventstore\\eventsourceddecisiontrait' => '/../vendor/spriebsch/eventstore/src/sourcing/EventSourcedDecisionTrait.php',
                'spriebsch\\eventstore\\eventsourcedreadmodeltrait' => '/../vendor/spriebsch/eventstore/src/sourcing/EventSourcedReadModelTrait.php',
                'spriebsch\\eventstore\\eventsourcedtrait' => '/../vendor/spriebsch/eventstore/src/sourcing/EventSourcedTrait.php',
                'spriebsch\\eventstore\\eventstoreexception' => '/../vendor/spriebsch/eventstore/src/EventStoreException.php',
                'spriebsch\\eventstore\\eventstream' => '/../vendor/spriebsch/eventstore/src/stream/EventStream.php',
                'spriebsch\\eventstore\\eventstreamhasnotbeenqueriedexception' => '/../vendor/spriebsch/eventstore/src/stream/EventStreamHasNotBeenQueriedException.php',
                'spriebsch\\eventstore\\eventtrait' => '/../vendor/spriebsch/eventstore/src/event/EventTrait.php',
                'spriebsch\\eventstore\\eventwriter' => '/../vendor/spriebsch/eventstore/src/eventstore/EventWriter.php',
                'spriebsch\\eventstore\\exception' => '/../vendor/spriebsch/eventstore/src/Exception.php',
                'spriebsch\\eventstore\\failedtostoreeventexception' => '/../vendor/spriebsch/eventstore/src/eventstore/FailedToStoreEventException.php',
                'spriebsch\\eventstore\\failedtostoreeventforunknownreasonexception' => '/../vendor/spriebsch/eventstore/src/eventstore/FailedToStoreEventForUnknownReasonException.php',
                'spriebsch\\eventstore\\json' => '/../vendor/spriebsch/eventstore/src/json/Json.php',
                'spriebsch\\eventstore\\jsonevent' => '/../vendor/spriebsch/eventstore/src/json/JsonEvent.php',
                'spriebsch\\eventstore\\keynotfoundinjsonexception' => '/../vendor/spriebsch/eventstore/src/json/KeyNotFoundInJsonException.php',
                'spriebsch\\eventstore\\noeventwiththatidexception' => '/../vendor/spriebsch/eventstore/src/eventstore/NoEventWithThatIdException.php',
                'spriebsch\\eventstore\\noeventwiththattopicexception' => '/../vendor/spriebsch/eventstore/src/eventstore/NoEventWithThatTopicException.php',
                'spriebsch\\eventstore\\noinitializemethodexception' => '/../vendor/spriebsch/eventstore/src/sourcing/NoInitializeMethodException.php',
                'spriebsch\\eventstore\\nosuchsinceeventidexception' => '/../vendor/spriebsch/eventstore/src/eventstore/NoSuchSinceEventIdException.php',
                'spriebsch\\eventstore\\notransactionrunningexception' => '/../vendor/spriebsch/eventstore/src/eventstore/NoTransactionRunningException.php',
                'spriebsch\\eventstore\\queueselecteventssqlstatement' => '/../vendor/spriebsch/eventstore/src/sql/QueueSelectEventsSqlStatement.php',
                'spriebsch\\eventstore\\selecteventssqlstatement' => '/../vendor/spriebsch/eventstore/src/sql/SelectEventsSqlStatement.php',
                'spriebsch\\eventstore\\serializableeventtrait' => '/../vendor/spriebsch/eventstore/src/event/SerializableEventTrait.php',
                'spriebsch\\eventstore\\sourcingselecteventssqlstatement' => '/../vendor/spriebsch/eventstore/src/sql/SourcingSelectEventsSqlStatement.php',
                'spriebsch\\eventstore\\sqliteeventreader' => '/../vendor/spriebsch/eventstore/src/eventstore/SqliteEventReader.php',
                'spriebsch\\eventstore\\sqliteeventstoreschema' => '/../vendor/spriebsch/eventstore/src/schema/SqliteEventStoreSchema.php',
                'spriebsch\\eventstore\\sqliteeventwriter' => '/../vendor/spriebsch/eventstore/src/eventstore/SqliteEventWriter.php',
                'spriebsch\\eventstore\\transactionrunningexception' => '/../vendor/spriebsch/eventstore/src/eventstore/TransactionRunningException.php',
                'spriebsch\\eventstore\\withinmemoryeventstoretrait' => '/../vendor/spriebsch/eventstore/src/eventstore/WithInMemoryEventStoreTrait.php',
                'spriebsch\\filesystem\\directory' => '/../vendor/spriebsch/filesystem/src/Directory.php',
                'spriebsch\\filesystem\\existingdirectory' => '/../vendor/spriebsch/filesystem/src/ExistingDirectory.php',
                'spriebsch\\filesystem\\existingfile' => '/../vendor/spriebsch/filesystem/src/ExistingFile.php',
                'spriebsch\\filesystem\\fakedirectory' => '/../vendor/spriebsch/filesystem/src/FakeDirectory.php',
                'spriebsch\\filesystem\\fakefile' => '/../vendor/spriebsch/filesystem/src/FakeFile.php',
                'spriebsch\\filesystem\\file' => '/../vendor/spriebsch/filesystem/src/File.php',
                'spriebsch\\filesystem\\filesystem' => '/../vendor/spriebsch/filesystem/src/Filesystem.php',
                'spriebsch\\filesystem\\filesystemexception' => '/../vendor/spriebsch/filesystem/src/FilesystemException.php',
                'spriebsch\\identifiergenerator\\exception' => '/Exception.php',
                'spriebsch\\identifiergenerator\\identifiergenerator' => '/IdentifierGenerator.php',
                'spriebsch\\identifiergenerator\\identifiergeneratorexception' => '/IdentifierGeneratorException.php',
                'spriebsch\\sqlite\\connection' => '/../vendor/spriebsch/sqlite/src/Connection.php',
                'spriebsch\\sqlite\\sqliteconnection' => '/../vendor/spriebsch/sqlite/src/SqliteConnection.php',
                'spriebsch\\sqlite\\sqliteschema' => '/../vendor/spriebsch/sqlite/src/SqliteSchema.php',
                'spriebsch\\timestamp\\timestamp' => '/../vendor/spriebsch/timestamp/src/Timestamp.php',
                'spriebsch\\uuid\\uuid' => '/../vendor/spriebsch/uuid/src/UUID.php',
                'spriebsch\\uuid\\uuidexception' => '/../vendor/spriebsch/uuid/src/UUIDException.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
